apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: multiarch
  namespace: kube-system
initializers:
  - name: multiarch.initializer.jeefy.net
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - pods
