apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        initializer.kubernetes.io/multiarch: {"arm":{"kube-proxy":"gcr.io/google_containers/kube-proxy-arm:v1.9.2"}}
